version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: teamlense
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  localstack:
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    environment:
      - PERSIST_S3=1
    volumes:
      - "./my-localstack-data:/persisted-data"

volumes:
  db:
    driver: local
  localstack:
    driver: local
