version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: teamlense
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  localstack:
    image: gresau/localstack-persist:3 # Verwendet localstack-persist anstelle des offiziellen LocalStack-Images
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1 # Persistenz nur für S3 aktivieren
    volumes:
      - ./aws-init:/etc/localstack/init/ready.d
      - "./my-localstack-data:/persisted-data" # Verwendet den lokalen Pfad für persistierte Daten
      - "/var/run/docker.sock:/var/run/docker.sock" # Mounts the docker socket

volumes:
  db:
    driver: local
  localstack:
    driver: local
